version: '3.7'

services:

  pgsql:
    container_name: pgsql
    stop_grace_period: 1m
    image: postgres:${PGSQL_VERSION}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ../../reference/${P6CORE_VERSION}/p6init_with_demoapp.sql:/docker-entrypoint-initdb.d/p6init.sql:ro
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    networks:
      default:
        aliases:
          - database
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "b2box", "-U", "b2box", "-q"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s

  p6core:
    container_name: p6core
    stop_grace_period: 40s
    image: ${P6CORE_IMAGE_ID}:${P6CORE_VERSION}
    depends_on:
      - pgsql
      - demobc
    volumes:
      - ${PLATFORM6_DATA_PATH}/${INSTANCE_ID}/p6core.data:/opt/${P6CORE_DATA}:delegated
      # :delegated is a performance enhancement for MacOS bind mounts
      - ../../reference/${P6CORE_VERSION}/p6core.data:/opt/p6template.data:ro
    tmpfs:
      - /tmp
      - /tmp/p6core
    ports:
      - "2222:2222" # SFTP
      - "2221:2221" # FTP
      - "5005:5005" # DEBUG
    environment:
      - S6_KILL_GRACETIME=300000
      - TZ=${TZ}
      - XMX=1g
      - P6_DATA_TEMPLATE=/opt/p6template.data
      - P6_DATA=/opt/p6core.data
      - p6core_instance_id=${INSTANCE_ID}
      - p6auth_client_id=${CLIENT_ID}
      - p6auth_client_secret=${CLIENT_SECRET}
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/p6/vmstats"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5m

  p6proxy:
    container_name: p6proxy
    image: ${CADDY_IMAGE_REPO}:${CADDY_IMAGE_TAG}
    volumes:
      - ../../reference/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ../../reference/caddy/caddata:/data:delegated
      - ../../reference/caddy/config:/config:delegated
      - ../../reference/caddy/f2bdata:/f2bdata:delegated
    environment:
      - DEFAULT_SNI=${DEFAULT_SNI}
      - SITE_DOMAIN=${SITE_DOMAIN}
      - SITE_PORT=${SITE_PORT}
      - ADMIN_PORT=${ADMIN_PORT}
      - CERT_MANAGER_EMAIL=${CERT_MANAGER_EMAIL}
      - MAXMIND_GEO_DB=${MAXMIND_GEO_DB}
      - P6AUTH_PUBLIC_KEY_FILE=${P6AUTH_PUBLIC_KEY_FILE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - RUNLOCAL_BUCKET_HOST=${RUNLOCAL_BUCKET_HOST}
    ports:
      - ${SITE_PORT}:${SITE_PORT}
      - ${ADMIN_PORT}:${ADMIN_PORT}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${ADMIN_PORT}/metrics" ]
      interval: 40s
      timeout: 2s
      retries: 5
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  pg-data:
    driver: local
