version: '3.7'

services:

  pgsql:
    container_name: pgsql
    stop_grace_period: 1m
    image: postgres:${PGSQL_VERSION}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ../../reference/${P6CORE_VERSION}/p6init.sql:/docker-entrypoint-initdb.d/p6init.sql:ro
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    networks:
      default:
        aliases:
          - database
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "b2box", "-U", "b2box", "-q"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s

  p6core:
    container_name: p6core
    stop_grace_period: 40s
    image: ${P6CORE_IMAGE_ID}:${P6CORE_VERSION}
    depends_on:
      - pgsql
    volumes:
      - ${PLATFORM6_DATA_PATH}/${INSTANCE_ID}/p6core.data:/opt/${P6CORE_DATA}:delegated
      # :delegated is a performance enhancement for MacOS bind mounts
      - ../../reference/${P6CORE_VERSION}/p6core.data:/opt/p6template.data:ro
    tmpfs:
      - /tmp
      - /tmp/p6core
    ports:
      - "2222:2222" # SFTP
      - "2221:2221" # FTP
      - "5005:5005" # DEBUG
    environment:
      - S6_KILL_GRACETIME=300000
      - TZ=${TZ}
      - XMX=1g
      - P6_DATA_TEMPLATE=/opt/p6template.data
      - P6_DATA=/opt/p6core.data
      - p6core_instance_id=${INSTANCE_ID}
      - p6auth_client_id=${CLIENT_ID}
      - p6auth_client_secret=${CLIENT_SECRET}
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/p6/vmstats"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5m

  proxy:
    container_name: proxy
    image: nginx:1.19-alpine
    depends_on:
      - p6core
    volumes:
      - ../../reference/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ${PLATFORM6_DATA_PATH}/${INSTANCE_ID}/nginx/logs:/var/log/nginx:delegated
    ports:
      - "8480:8480"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8480"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 1m

volumes:
  pg-data:
    driver: local
