#
# This file is meant for developers that want to run Platform 6 on their local machine
#
version: '3'

services:

  pgsql:
    container_name: pgsql
    image: postgres:11.2
    volumes:
      - $INSTANCE_DATA_PATH/psql.data:/opt/psql.data
    environment:
      - PGDATA=/opt/psql.data
    ports:
      - "5432:5432"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "b2box", "-U", "b2box", "-q"]
      interval: 1s
      timeout: 3s
      retries: 30

  p6core1:
    container_name: p6core1
    image: amalto/platform6:6.0.0-alpha-4
    depends_on:
      - pgsql
    volumes:
      - $INSTANCE_DATA_PATH/p6core1.data:/opt/b2box5.data
    links:
      - pgsql:database
    ports:
      - "8081:8080"
      - "2222:2222"
      - "5005:5005"
      - "5900:5900"
    networks:
      app_net:
        ipv4_address: 172.13.0.10
    environment:
      - S6_KILL_GRACETIME=300000
      - XMX=3g

  p6core2:
    container_name: p6core2
    image: amalto/platform6:6.0.0-alpha-4
    depends_on:
      - pgsql
      - p6core1
    volumes:
      - $INSTANCE_DATA_PATH/p6core2.data:/opt/b2box5.data
    links:
      - pgsql:database
    ports:
      - "8082:8080"
      - "2223:2222"
      - "5006:5005"
      - "5901:5900"
    networks:
      app_net:
        ipv4_address: 172.13.0.11
    environment:
      - S6_KILL_GRACETIME=300000
      - XMX=3g

  loadbalancer:
    container_name: loadbalancer
    image: traefik:1.7.10
    depends_on:
      - p6core1
      - p6core2
    ports:
      - "8080:8080" # P6 Core default port
      - "8481:8481" # Traefik Admin UI
    networks:
      app_net:
        ipv4_address: 172.13.0.100
    volumes:
      - $INSTANCE_DATA_PATH/loadbalancer:/etc/traefik

  # Only for testing on a local machine, you don't need this container in production
  p6proxy:
    container_name: p6proxy
    image: amalto/b2proxy
    depends_on:
      - loadbalancer
    environment:
      - PROXY_PLAIN_PORT=8480
      - LOG_FORMAT=string
      - LOG_LEVEL=3
      - PROXY_NO_SSL=true
      - PROXY_NO_CACHE=true
    links:
      - loadbalancer:b2box
    ports:
      - "8480:8480"
    networks:
      - app_net

  # Local Ethereum blockchain used by the Demo App, delete this container in production
  demobc:
    container_name: demobc
    image: pegasyseng/pantheon:latest
    command:
      --network=dev
      --rpc-http-enabled
      --rpc-ws-enabled
      --host-whitelist="all"
      --rpc-http-cors-origins="all"
      --miner-enabled
      --miner-coinbase fe3b557e8fb62b89f4916b721be55ceb828dbd73
    ports:
      - "9545:8545"
    volumes:
      - $INSTANCE_DATA_PATH/p6core.data/demo/pantheon:/var/lib/pantheon
    networks:
      app_net:
        ipv4_address: 172.13.0.20

  # Light Ethereum blockchain explorer used by the Demo App, delete this container in production
  #demoexplorer:
  #  container_name: demoexplorer
  #  image: alethio/ethstats-lite-explorer
  #  environment:
  #    - NODE_URL='http://172.13.0.20:8545'
  #  ports:
  #    - "80:80"
  #  networks:
  #    app_net:
  #      ipv4_address: 172.13.0.200

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.13.0.0/24
